const fs = require('fs');
const https = require('https');
const path = require('path');

// Create assets directory if it doesn't exist
const assetsDir = path.join(__dirname, 'assets', 'images');
if (!fs.existsSync(assetsDir)) {
    fs.mkdirSync(assetsDir, { recursive: true });
}

// Note: This script is kept for reference but is no longer used.
// The game now uses SVG images generated by generate-assets.js

console.log('This script is deprecated. Please use generate-assets.js instead.');
console.log('Run: node generate-assets.js'); 